version: '3.4'

services:
  # client:
  #     build:
  #       context: ./client
  #       dockerfile: Dockerfile
  #     image: jjs98/meter-reading-client
  #     ports:
  #       - "5000:80"

  # api:
  #     build:
  #       context: ./server
  #       dockerfile: Dockerfile
  #     image: jjs98/meter-reading-api
  #     environment:
  #       ConnectionStrings__AppDbContext: Server=db;Port=5432;Database=MeterReading;User Id=postgres;Password=p@ssw0rd;
  #     ports:
  #       - "8081:80"
  #     depends_on:
  #       - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p@ssw0rd
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
